spring:
  application:
    name: msvc-management
  config:
    import:
      - optional:configserver:http://localhost:8888
      - env.properties
  kafka:
    bootstrap-servers: localhost:9092


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true