spring:
  application:
    name: msvc-management
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/urooms

  kafka:
    bootstrap-servers: localhost:9092