server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: publications
          uri: http://localhost:9090
          predicates:
            - Path=/api/v2/URooms/**
        - id: accounts
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/URooms/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: reviews
          uri: http://localhost:9070
          predicates:
            - Path=/api/v3/URooms/**
        - id: managements
          uri: http://localhost:9060
          predicates:
            - Path=/api/v4/URooms/**
        - id: accounts-create-user
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/URooms/keycloak/user
            - Method=POST
          filters:
            - RemoveRequestHeader=Authorization
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8180/realms/urooms
        registration:
          urooms-client:
            provider: keycloak
            client-id: urooms-client
            client-secret: YHtytGJdn6pH0WSNFj9za8jZW3q1KJ3q
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid